[package]
name = "pdfsan-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = { version = "0.34", default-features = false, features = ["nom_parser", "chrono_time"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
flate2 = "1"
thiserror = "1"
tokio-util = { version = "0.7", features = ["rt"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
